from selenium import webdriver
from selenium.webdriver.support.select import Select
import time

driver = webdriver.Chrome('/usr/bin/chromedriver')
driver.maximize_window()
driver.get('http://demo.automationtesting.in/Register.html')
window = driver.current_url #получение адреса, переход не происходит
print(window)
first_name = driver.find_element_by_xpath('//*[@id="basicBootstrapForm"]/div[1]/div[1]/input').send_keys('kriril')
last_name = driver.find_element_by_xpath('//*[@id="basicBootstrapForm"]/div[1]/div[2]/input').send_keys('kirilov')
email = driver.find_element_by_xpath('//*[@id="eid"]/input').send_keys("qwerty@mail.com")
phone = driver.find_element_by_xpath('//*[@id="basicBootstrapForm"]/div[4]/div/input').send_keys('1234567890')
gender = driver.find_element_by_xpath('//*[@id="basicBootstrapForm"]/div[5]/div/label[1]/input').click()
time.sleep(2)
countries = driver.find_element_by_id('countries')
select = Select(countries)
select.select_by_value('Finland')
time.sleep(2)
year = driver.find_element_by_id('yearbox')
select = Select(year)
select.select_by_value('1990')
time.sleep(2)
month= driver.find_element_by_xpath('//*[@id="basicBootstrapForm"]/div[11]/div[2]/select')
select = Select(month)
select.select_by_value('June')
time.sleep(2)
day = driver.find_element_by_id('daybox')
select = Select(day)
select.select_by_value('25')
time.sleep(2)
password = driver.find_element_by_id('firstpassword').send_keys('Qwerty123')
confium_password = driver.find_element_by_id('secondpassword').send_keys('Qwerty123')
file = "/home/grins/Без названия.jpeg"
upload = driver.find_element_by_id('imagesrc')
upload.send_keys(file)
driver.execute_script("window.scrollBy(0, 300)")
time.sleep(10)
sub = driver.find_element_by_id('submitbtn').click()
